### ISSUE TITLE
Add instances for "stricter" WriterT

### ISSUE THREAD

**Issue by ocramz** [ekmett/exceptions#57]
I found myself needing the MonadThrow and MonadCatch instances of the CPS version of WriterT , so I understand they should appear here in `exceptions` instead.

https://hackage.haskell.org/package/writer-cps-transformers
https://hackage.haskell.org/package/writer-cps-mtl

**Comment by snoyberg** [comment]
It would make more sense from a dependency standpoint to add the instances in writer-cps-transformers instead.

**Comment by ocramz** [comment]
You're right; I'll re-route this ticket
